# Generated by Django 4.2.26 on 2025-11-20 05:14

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.conf import settings


def forwards_func(apps, schema_editor):
    """
    Promote all non-staff, non-superuser users to Contributor group.
    
    - Ensures Contributor group exists
    - Adds all regular users to Contributor group
    - Optionally removes them from Reader group if it exists
    """
    # Get the User model
    User = get_user_model()
    
    # Get or create the Contributor group
    contributor_group, created = Group.objects.get_or_create(name=settings.CONTRIBUTOR_GROUP)
    
    # Try to get the Reader group (may not exist)
    reader_group = Group.objects.filter(name=settings.READER_GROUP).first()
    
    # Find all non-staff, non-superuser users
    regular_users = User.objects.filter(is_staff=False, is_superuser=False)
    
    updated_count = 0
    for user in regular_users:
        # Add user to Contributor group if not already there
        if not user.groups.filter(name=settings.CONTRIBUTOR_GROUP).exists():
            user.groups.add(contributor_group)
            updated_count += 1
        
        # Remove user from Reader group if it exists and user is in it
        if reader_group and user.groups.filter(name=settings.READER_GROUP).exists():
            user.groups.remove(reader_group)


def reverse_func(apps, schema_editor):
    """
    Reverse migration: do nothing (or optionally move users back to Reader).
    For this project, a no-op reverse is acceptable.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
