# Generated by Django 4.2.26 on 2025-12-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promote_readers_to_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(db_index=True, max_length=100)),
                ('variant', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('exposure', 'Variant Shown'), ('click', 'Button Clicked')], db_index=True, max_length=20)),
                ('session_id', models.CharField(db_index=True, help_text='Cookie-based session identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_forced', models.BooleanField(default=False, help_text='True if variant was forced via ?force_variant parameter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experiment_name', 'variant', 'event_type'], name='core_abtest_experim_03add3_idx'), models.Index(fields=['experiment_name', 'created_at'], name='core_abtest_experim_0b9b82_idx')],
            },
        ),
    ]
