# Generated by Django 4.2.26 on 2025-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abtestevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abtestevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'AB Test Event', 'verbose_name_plural': 'AB Test Events'},
        ),
        migrations.AddField(
            model_name='abtestevent',
            name='endpoint',
            field=models.CharField(default='/218b7ae/', help_text="Endpoint path, e.g. '/218b7ae/'", max_length=200),
        ),
        migrations.AddField(
            model_name='abtestevent',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, help_text='User identifier if available (from Django User or session)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abtestevent',
            name='event_type',
            field=models.CharField(choices=[('exposure', 'Variant Shown'), ('conversion', 'Button Clicked')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='abtestevent',
            name='experiment_name',
            field=models.CharField(db_index=True, help_text="Experiment identifier, e.g. 'button_label_kudos_vs_thanks'", max_length=100),
        ),
        migrations.AlterField(
            model_name='abtestevent',
            name='variant',
            field=models.CharField(db_index=True, help_text="Variant identifier, e.g. 'kudos' or 'thanks'", max_length=20),
        ),
        migrations.AddIndex(
            model_name='abtestevent',
            index=models.Index(fields=['endpoint', 'event_type'], name='core_abtest_endpoin_0391bb_idx'),
        ),
    ]
