# Generated by Django 4.2.26 on 2025-12-09 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_normalize_abtestevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abtestevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='abtestevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Django User if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abtestevent',
            name='event_type',
            field=models.CharField(choices=[('exposure', 'Exposure'), ('conversion', 'Conversion')], db_index=True, max_length=32),
        ),
    ]
