# Generated by Django 4.2.26 on 2025-11-12 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Housing, Food)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class name (e.g., 'house-door', 'cup-hot')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Post content (Markdown supported)')),
                ('summary', models.TextField(blank=True, help_text='Brief summary for listings (optional)', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status in the approval workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically when status changes to approved', null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the post', null=True, upload_to='posts/')),
                ('author', models.ForeignKey(help_text='User who created this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='guide.category')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title', max_length=200)),
                ('url', models.URLField(help_text='External URL')),
                ('description', models.TextField(blank=True, help_text='Description of the link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category association', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='guide.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='guide_categ_slug_56395a_idx'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(help_text='Post that was bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='guide.post'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(help_text='User who bookmarked this post', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='guide_post_status_15c481_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='guide_post_categor_2c7e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['updated_at'], name='guide_post_updated_33eeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='guide_post_slug_199dca_idx'),
        ),
        migrations.AddIndex(
            model_name='externallink',
            index=models.Index(fields=['category'], name='guide_exter_categor_e7941a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'post'], name='guide_bookm_user_id_1c2064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'post')},
        ),
    ]
